### ISSUE TITLE
[question] How to get current color in happy-hare ?

### ISSUE THREAD

**Issue by EdwinPock** [moggieuk/Happy-Hare#520]
I want to add in my macro after loading. Which extrudes a specific amount of filament (no cleaning tower).
So that the amount of filament to be extruded depends on the color. First of all, I am talking about the white color which requires more "cleaning". 
```g-code
   {% set gate_color = printer['mmu']['gate_color'] %}
  #{% set gate_color = printer['mmu']['gate_color_rgb'] %}
  {% set rgb = gate_color[gate_color] %}
  {% if rgb == "ffffff" %}
    SET_LED LED="hotend_rgb" RED=1 GREEN=0 BLUE=0 SYNC=0 TRANSMIT=1
    G1 X1 Y1 F6000
    G1 E140 F600
  {% else %}
    SET_LED LED="hotend_rgb" RED=1 GREEN=1 BLUE=1 SYNC=0 TRANSMIT=1
    G1 X1 Y1 F6000
    G1 E80 F600
  {% endif %}
  
``` 
But it doesn't recognize the color. I don't know if I'm using the right variables.
How to get current color in happy-hare ?

**Comment by moggieuk** [comment]
I think the easiest way is to use:
```
printer.mmu.active_filament
```
It will be structured like this:
```yml
DEBUG_SEARCH_VARS S="active_filament"
printer.mmu.active_filament.filament_name : Orange Pie
printer.mmu.active_filament.material : TPU
printer.mmu.active_filament.color : dc6834
printer.mmu.active_filament.spool_id : 3
printer.mmu.active_filament.temperature : 185
```

You can also get the current gate `printer.mmu.gate` and index into `printer.mmu.gate_color` as you are doing.
