### ISSUE TITLE
Orcaslicer + klipper +Spoolman+ happy-hare

### ISSUE THREAD

**Issue by Romano26** [moggieuk/Happy-Hare#612]
Hi
i need help, i use orcaslicer with spoolman for filament management.
i used the tutorial to assign the filament to the gate but it doesn't work, no change

![Image](https://github.com/user-attachments/assets/32b9ff97-fbd0-4961-b512-83138c53dbcf)

does it work for you ?

**Comment by moggieuk** [comment]
If you run `MMU_GATE_MAP` do you see the spoolID on each gate? E.g.
```yml
mmu_gate_map
Gates / Filaments:
Gate 0: Status: Spool, SpoolId: 1 --> Material: PLA - Silk, Color: 8cdfac, Name: Matte Green, Temp: 210
Gate 1: Status: Spool, SpoolId: 2 --> Material: PTEG, Color: dcda34, Name: eMarble, Temp: 220
```

If so then filament details are being pulled from spoolman.  If not and you are sure you set the `spoolman_support` parameter? It has to not be "off" for this to work.

Finally, if you want spoolman to be the source of truth (unusually unless in print farm) then you would set `spoolman_support: pull` and set the gate assignment in spoolman database, either directly or with the `MMU_SPOOLMAN` command (which is a direct write to the DB).
